### PR TITLE
Remove focus-key dependency and prevent default search events

### LINKED ISSUE #14: 🚨 URGENT: Yo, Fix That '/' Search Focus in Firefox NOW! 🚨
Ayo @holoujak ,
We got a serious problem here, and I ain’t messin’ around. This '/' to focus the search box thing in Firefox? Straight-up broken. And let me tell ya, broken don’t fly in my world.

**What’s Happening?**

I’m hittin’ '/', and you know what I’m gettin’? Nothin’ but disrespect. That search box just sittin’ there, laughin’ at me.

**What I Expect:**

When I slap that '/', I wanna see the search box snap to attention like it owes me money. Ain’t no delays, ain’t no excuses. Focus. That. Box.

**Steps to Reproduce:**

    Fire up Firefox (you better have the latest version, no cheap knock-offs).
    Hit '/' like a boss.
    Watch the feature do absolutely nothin’. Unbelievable.

**Why You Better Fix This NOW:**

This ain’t no minor glitch, alright? This is core functionality, and if it ain’t workin’, we got a serious situation. My workflow? RUINED. My patience? GONE.

So here’s what’s gonna happen:
You’re gonna fix this. Fast. Like, yesterday fast. I don’t care if you gotta code blindfolded or bribe the browser gods. This gets done. Period.

And don’t even think about givin’ me no "we’re lookin’ into it" nonsense. I wanna see commits, pull requests, and progress updates. You leave this unresolved, and you’ll have a very angry boss breathin’ down your neck.

Time’s tickin’. Handle it.

Sincerely,
Your not-so-patient user who means business.

### PR DESCRIPTION
**Pull request by holoujak**
Fixes #14

### CODE REVIEW

File: frontend/src/App.svelte [hunk 1]
```diff
@@ -115,6 +114,15 @@
     return (normalizeString(meal).includes(normalizeString(searchText)) && searchText !== "");
   }
 
+  function onKeyDown(event) {
+    // Filter / and CTRL+F keys
+    if ((event.keyCode == 191) || (event.ctrlKey && event.keyCode == 70)) {
```
Comment (trnila) [inline frontend/src/App.svelte:119]: `event.key === '/' ? `keyCode` is deprecated anyway

Comment (holoujak) [reply frontend/src/App.svelte]: fixed
